---
title: "Code Book"
output: html_document
---

First call the dplyr package and the reshape2 package. 

```
library(dplyr)
library(reshape2)
```

The dataset used for this analysis is located at http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones.  Download the file and unzip it.

```
dataset_url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(dataset_url, "data.zip")
unzip("data.zip", exdir = "data")
```
### Read in the data and create an input dataset
First we will read in the X_train, X_test and features datasets. The X_train and X_test datasets will be combined to create 1 dataset and the features will be the variables of that dataset

```
X_train <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/train/X_train.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

X_test <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/test/X_test.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

features <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/features.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

x_total <- rbind(X_train, X_test)

names(x_total) <- features[,2]
```

Next the y_train and y_test datasets will be read in and combined into 1 dataset.  The first and only variable in that dataset will be renamed to  measurementid.
```
y_train <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/train/y_train.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)
y_test <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/test/y_test.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

y_total <- rbind(y_train, y_test)

y_total <- rename(y_total, measurementid = V1)
```

The subject_test and subject_train datasets will be read in and combined as well.  The first and only variable in this dataset will be renamed to subjectid

```
subject_test <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/test/subject_test.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

subject_train <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/train/subject_train.txt", quote="\"", comment.char="", stringsAsFactors=FALSE)

sub_total <- rbind(subject_train, subject_test)

subject_total <- rename(sub_total, subjectid = V1)
```

Cbind all 3 datasets together to create our final input dataset
```
data <- cbind(subject_total, y_total, x_total) 
```

### Keep only the variables that represent the mean or standard deviation of a measurement.
```
mean_std_vars <- (grep("[Mm]ean|[Ss]tandard [Dd]eviation|[Ss]td", names(data)))
data_mean_std <- data[ ,mean_std_vars]
data2 <- cbind(subject_total, y_total, data_mean_std)
```
### Use descriptive activity names instead of numbers in the measurementid column

Read in activity_labels
```
activity_labels <- read.table("C:/Users/Calli6/Desktop/Getting and Cleaning Data/data/UCI HAR Dataset/activity_labels.txt"", quote="\"", comment.char="", stringsAsFactors=FALSE)
```
Lower case the values in activitydescription and remove underscores
```
activity_labels_rn <-sapply(2, function(x,y) tolower(y[,x]), y = activity_labels)
activity_labels_rm <- as.data.frame(sub("_"," ", activity_labels_rn))
```
Join activity_labels_rm to activity_labels
```
activity_labels_3 <- cbind(activity_labels, activity_labels_rm)
activity_labels_edit <- activity_labels_3[,c(1,3)]
```
Rename V2 in activity_labels to activitydescription and Rename V1 to measurementid
```
activity_labels <- rename(activity_labels_edit, activitydescription = V1.1, measurementid = V1)
```
Join 
```
data_activity <- inner_join(activity_labels, data2, by = "measurementid")
data_activity <- data_activity[,-1]
```

### Remove underscores, commas, from the variable  names and make sure they are all lower case 
```
data_lower<- tolower(names(data_activity))
data_rm <- (gsub("\\(|\\)|-|_|,", "", data_lower))
as.vector(data_rm)
names(data_activity) <- data_rm
```

### Create a dataset that has the average of each variable for each activity and for each subject 
```
data_melt <- melt(data_activity, id = c("activitydescription","subjectid"))
decast_data <- dcast(data_melt, activitydescription + subjectid ~ variable, mean)
```
### The variables in the final dataset contain the average measure for a subject for a certain activity
* activitydescription
* subjectid
* tbodyaccmeanx
* tbodyaccmeany
* tbodyaccmeanz
* tbodyaccstdx
* tbodyaccstdy
* tbodyaccstdz
* tgravityaccmeanx
* tgravityaccmeany
* tgravityaccmeanz
* tgravityaccstdx
* tgravityaccstdy
* tgravityaccstdz
* tbodyaccjerkmeanx
* tbodyaccjerkmeany
* tbodyaccjerkmeanz
* tbodyaccjerkstdx
* tbodyaccjerkstdy
* tbodyaccjerkstdz
* tbodygyromeanx
* tbodygyromeany
* tbodygyromeanz
* tbodygyrostdx
* tbodygyrostdy
* tbodygyrostdz
* tbodygyrojerkmeanx
* tbodygyrojerkmeany
* tbodygyrojerkmeanz
* tbodygyrojerkstdx
* tbodygyrojerkstdy
* tbodygyrojerkstdz
* tbodyaccmagmean
* tbodyaccmagstd
* tgravityaccmagmean
* tgravityaccmagstd
* tbodyaccjerkmagmean
* tbodyaccjerkmagstd
* tbodygyromagmean
* tbodygyromagstd
* tbodygyrojerkmagmean
* tbodygyrojerkmagstd
* fbodyaccmeanx
* fbodyaccmeany
* fbodyaccmeanz
* fbodyaccstdx
* fbodyaccstdy
* fbodyaccstdz
* fbodyaccmeanfreqx
* fbodyaccmeanfreqy
* fbodyaccmeanfreqz
* fbodyaccjerkmeanx
* fbodyaccjerkmeany
* fbodyaccjerkmeanz
* fbodyaccjerkstdx
* fbodyaccjerkstdy
* fbodyaccjerkstdz
* fbodyaccjerkmeanfreqx
* fbodyaccjerkmeanfreqy
* fbodyaccjerkmeanfreqz
* fbodygyromeanx
* fbodygyromeany
* fbodygyromeanz
* fbodygyrostdx
* fbodygyrostdy
* fbodygyrostdz
* fbodygyromeanfreqx
* fbodygyromeanfreqy
* fbodygyromeanfreqz
* fbodyaccmagmean
* fbodyaccmagstd
* fbodyaccmagmeanfreq
* fbodybodyaccjerkmagmean
* fbodybodyaccjerkmagstd
* fbodybodyaccjerkmagmeanfreq
* fbodybodygyromagmean
* fbodybodygyromagstd
* fbodybodygyromagmeanfreq
* fbodybodygyrojerkmagmean
* fbodybodygyrojerkmagstd
* fbodybodygyrojerkmagmeanfreq
* angletbodyaccmeangravity
* angletbodyaccjerkmeangravitymean
* angletbodygyromeangravitymean
* angletbodygyrojerkmeangravitymean
* anglexgravitymean
* angleygravitymean
* anglezgravitymean

